### ISSUE TITLE
Add flag that only ouputs the number of lib years

### ISSUE THREAD

**Issue by WyriHaximus** [ecoAPM/php-libyear#112]
As a package maintainer, I want to have a flag that only outputs the number of lib years, so that as a package maintainer I can rank my packages on how far behind they are and decide which to update first.

I'm more than happy to write the PR adding said flag if it is a welcome addition.

**Comment by SteveDesmond-ca** [comment]
Hi, and thanks for bringing this up! I'm a little unclear on what you're looking for / what's being asked, but if it's just that the final total number of libyears behind is output on its own, that can be accomplished with some pipegrepping:
```bash
$ php libyear | tail -n1 | sed 's/[^0-9.]*//g'
```
This gets only the final line, and outputs only the number part of the text.

Does that meet your needs, or are you looking for something different / more specific?

**Comment by WyriHaximus** [comment]
> Hi, and thanks for bringing this up! I'm a little unclear on what you're looking for / what's being asked, but if it's just that the final total number of libyears behind is output on its own, that can be accomplished with some pipegrepping:

Yes it's purely just that number

> Does that meet your needs, or are you looking for something different / more specific?

That meets my needs perfectly, thanks :+1:
